### DISCUSSION TITLE
Issue Assigning GitHub Team as Reviewer within Enterprise -- Works with auto-assigning groups, and individuals

### DISCUSSION THREAD

**Discussion by chrockhill12** [necojackarc/auto-request-review#120] [Q&A]
Config file: 
```
reviewers:
  # The default reviewers
  defaults: # currently defaults to the default reviewers.  Will randomly assign one of them (or 2 depending on "number of reviewers" config)
      - team:mds-platform
      - crockhill_sfemu

  groups:
  #MDS-Platforms  
      mds-plaform-approver:
        - crockhill_sfemu

  per_author:
  # MDS Platforms Review Assignments
      mds-plaform-approver:
        - team:mds-platform


  options:
    ignore_draft: true
    ignored_keywords:
      - DO NOT REVIEW
    enable_group_assignment: true

    # Randomly pick reviewers up to this number.
    # Do not set this option if you'd like to assign all matching reviewers.
    number_of_reviewers: 1
    #update

    # If it's true, the last matching files-change pattern takes the most precedence (CODEOWNERS-compatible)
  
    # last_files_match_only: false
```

Error with team having proper access to the repo:

```
Run mds-emu/mds-emu-mds-auto-request-review-action@v1.1.1
Fetching configuration file from the source branch
Fetching changed files in the pull request
Identifying reviewers based on the changed files
A "files" key does not exist in config; returning no reviewers for changed files.
Identifying reviewers based on the author
Adding other group members to reviewers if group assignment feature is on
Group assignment feature is disabled
Randomly picking reviewers if the number of reviewers is set
Requesting review to team:mds-platform
Error: HttpError: Validation Failed: "Could not resolve to a node with the global id of 'T_kwDOBzcd9M4Adqj[8](https://github.com/mds-emu/CR-Test-Repo/actions/runs/9117703018/job/25113345970#step:2:9)'."
```

Error when I remove the team from access the repo: 
```
Error: HttpError: Reviews may only be requested from collaborators. One or more of the teams you specified is not a collaborator of the mds-emu/CR-Test-Repo repository.
```
