### ISSUE TITLE
What is the permission required?

### ISSUE THREAD

**Issue by bluven** [necojackarc/auto-request-review#105]
I already used "write-all", but my action still failed:
```
Run necojackarc/auto-request-review@v0.12.0
Fetching configuration file from the source branch
Fetching changed files in the pull request
Identifying reviewers based on the changed files
A "files" key does not exist in config; returning no reviewers for changed files.
Identifying reviewers based on the author
"per_author" is not set; returning no reviewers for the author.
Adding other group members to reviewers if group assignment feature is on
Group assignment feature is disabled
Matched no reviewers
Falling back to the default reviewers
Randomly picking reviewers if the number of reviewers is set
Requesting review to bluven
Error: HttpError: Resource not accessible by integration
```

**Comment by ianchesal** [comment]
This worked for me:

```
name: Auto Request Review

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Request review based on files changed and groups the author belongs to
        uses: necojackarc/auto-request-review@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml
```
