### ISSUE TITLE
Unable to use github team

### ISSUE THREAD

**Issue by litepl** [necojackarc/auto-request-review#106]
Hello,

I just don't know what I'm doing wrong...

workflow

```
name: Add default reviewers
run-name: Add default reviewers
on:
  pull_request:
    types: [opened, ready_for_review, reopened]
jobs:
  add-default-reviewers:
    runs-on: self-hosted
    steps:
      - name: Auto Request Review
        uses: necojackarc/auto-request-review@v0.12.0
        with:
          token: ${{ secrets.PAT_FOR_AUTO_REQUEST_REVIEW }}
          config: .github/reviewers.yaml
```

reviewers.yaml
```
reviewers:
  defaults:
    - team:devops
options:
  ignore_draft: true
```

PAT_FOR_AUTO_REQUEST_REVIEW has full access to all repos

The funny thing is, when I remove devops team from collaborators the job succeed but no reviewers are added. When I'm adding it with admin role, the error is: 

```Requesting review to team:devops
Error: HttpError: Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the HardRockDigital/lt-test repository.
```
