### ISSUE TITLE
"explode" GitHub team when using as a reviewer group

### ISSUE THREAD

**Issue by pd93** [necojackarc/auto-request-review#107]
In our pipeline we have a config similar to this: 

```yml
reviewers:
  defaults:
    - team:a

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    a:
      - team:a
    b: 
      - team:b
     
  "**/*.go":
    - team:a
  "**/*.js":
    - team:b

options:
  ignore_draft: true
  number_of_reviewers: 2
```

At the moment, this will assign the actual GitHub team for the given file changes. I would like it to assign 2 _users_ from inside these teams instead of the team as a whole. Is this possible? It would allow us to manage the groups via GitHub rather than listing users in the config manually which requires us to commit changes any time the teams change.
