### ISSUE TITLE
Github Team doesn't work as a group

### ISSUE THREAD

**Issue by josh-bartz** [necojackarc/auto-request-review#109]
I have a github team that I'm trying to automatically request reviews by all team members, for all team members.

Ex: team-1 consists of [dev1, dev2, dev3]. If dev2 submits a PR, I want dev1 and dev3 to be requested automatically. However, only the following seems to work:

```
reviewers:
  groups:
    group-1
      - dev1
      - dev2
      - dev3

  per_author:
    group-1
      - team:team-1
```

I would have expected this to work, too:

```
reviewers:
  groups:
    group-1
      - team:team-1

  per_author:
    group-1
      - team:team-1
```

Setting `enable_group_assignment: true` doesn't work, either. Is there a way to do this that I'm missing?

**Comment by olivermeyer** [comment]
Facing a similar issue. Here's my configuration file:
```
reviewers:
  groups:
    group1:
      - user1
      - user2

files:
  'somefiles/**':
    - group1
    - team:team1

options:
  number_of_reviewers: 2
  enable_group_assignment: true
```
When making changes to files inside `somefiles/`, I would expect the workflow to request a review from one member of `group1` and one member of `team1`. In practice, it requests a review from one member of group1 as expected, but not from team2. The logs don't say anything about the team at all. I'm probably missing something but can't figure out what.

**Comment by swrobel** [comment]
I'm using exactly the style of config in your second example, with these config options, and it works great!

```
options:
  enable_group_assignment: false
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
    - WIP
  number_of_reviewers: 1
```
