### ISSUE TITLE
"last_files_match_only" does not work when pattern owner is a team

### ISSUE THREAD

**Issue by Warwolt** [necojackarc/auto-request-review#111]
## Problem
When I have a pattern with a team set as reviewer, and a more specific pattern with a specific individual as reviewer, and have `last_files_match_only = true`, I get both the team and the individual as reviewers when changing the file for the specific pattern.

Expected behavior would be that _only_ the specific individual is assigned as reviewer. 

Note: If both the general and the specific pattern have individuals as reviewers the behavior is as expected. This bug _only_ happens when the general pattern has a _team_ as reviewer.  

Mock up screenshot of what's happening:

![image](https://github.com/necojackarc/auto-request-review/assets/23612880/f7fb596c-26e3-437b-96d8-263d9f8d2024)

Expected behavior:

![image](https://github.com/necojackarc/auto-request-review/assets/23612880/156f826f-f45f-494d-b71f-b198187398c5)

## Context

I have the following `CODEOWNERS` reference file (with the actual organization and team names changed):

```codeowners
src/gui/ @MyOrg/some-team
src/gui/gui.c @specific-user
```

I have the following `reviewers.yaml` file: 

```yaml
files:
  'src/gui/**':
    - team:some-team
  'src/gui/gui.c':
    - specific-user

last_files_match_only: true
```

I have the following workflow:

```yaml
name: Auto Request Review

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto_request_review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request review based on files changes and/or groups the author belongs to
        uses: necojackarc/auto-request-review@v0.12.0
        with:
          token: ${{ secrets.PAT_FOR_AUTO_REQUEST_REVIEW }}
          config: ./reviewers.yaml
          use_local: true

```
