### ISSUE TITLE
"last_files_match_only=true" only adds one alias as a reviewer, regardless of number of edited files

### ISSUE THREAD

**Issue by jamoor-moj** [necojackarc/auto-request-review#115]
## Problem

Currently, I have a repository with the action setup to have `last_files_match_only=true`. When I open a PR with multiple files edited inside the PR that each have their own alias associated with them, I would expect that a single alias for each file edited would be added to the PR.

codereviewers.yml
```
files:
  'include/client.h':
    - jamoor-john-doe
  'src/**':
    - jamoor
  'src/client.cpp':
    - jamoor-test
options:
  ignore_draft: true
  last_files_match_only: true
```

Changes in PR
![image](https://github.com/necojackarc/auto-request-review/assets/148133800/8d63bf9c-8f25-46ac-99d7-f6aa882781ef)

### Expected Behavior
![image](https://github.com/necojackarc/auto-request-review/assets/148133800/268d93f3-b5eb-4898-8907-65957f1aa50c)

### Actual Behavior
![image](https://github.com/necojackarc/auto-request-review/assets/148133800/36935571-13e0-4d95-9508-80a62da6c6c8)

## Context

Based on the PR that added the `last_files_match_only=true` functionality (https://github.com/necojackarc/auto-request-review/pull/80), it looks like the intention was to have the `files` section of `codereviewers.yml` to match the behavior of github's `codeowners` file.

I've setup a test repo (https://github.com/jamoor-moj/codereview_demo) that I can compare the behavior of `codeowners` and `codereviewers` (which is where I got the screenshots of the behavior above)

Codeowners: https://github.com/jamoor-moj/codereview_demo/pull/4
```
  include/client.h @jamoor-john-doe
  src/ @jamoor
  src/client.cpp @jamoor-test
```

Codereviewers: https://github.com/jamoor-moj/codereview_demo/pull/5
```
files:
  'include/client.h':
    - jamoor-john-doe
  'src/**':
    - jamoor
  'src/client.cpp':
    - jamoor-test
options:
  ignore_draft: true
  last_files_match_only: true
```

Is my understanding correct that this was the intention and therefore this is a bug? Or was that not the intention and this is an enhancement?
