### ISSUE TITLE
Issue Assigning GitHub Team as Reviewer within Enterprise -- Works with auto-assigning groups, and individuals

### ISSUE THREAD

**Issue by chrockhill12** [necojackarc/auto-request-review#121]
### Discussed in https://github.com/necojackarc/auto-request-review/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **chrockhill12** May 17, 2024</sup>
Config file: 
```
reviewers:
  # The default reviewers
  defaults: # currently defaults to the default reviewers.  Will randomly assign one of them (or 2 depending on "number of reviewers" config)
      - team:mds-platform
      - crockhill_sfemu

  groups:
  #MDS-Platforms  
      mds-plaform-approver:
        - crockhill_sfemu

  per_author:
  # MDS Platforms Review Assignments
      mds-plaform-approver:
        - team:mds-platform


  options:
    ignore_draft: true
    ignored_keywords:
      - DO NOT REVIEW
    enable_group_assignment: true

    # Randomly pick reviewers up to this number.
    # Do not set this option if you'd like to assign all matching reviewers.
    number_of_reviewers: 1
    #update

    # If it's true, the last matching files-change pattern takes the most precedence (CODEOWNERS-compatible)
  
    # last_files_match_only: false
```

Error with team having proper access to the repo:

```
Run mds-emu/mds-emu-mds-auto-request-review-action@v1.1.1
Fetching configuration file from the source branch
Fetching changed files in the pull request
Identifying reviewers based on the changed files
A "files" key does not exist in config; returning no reviewers for changed files.
Identifying reviewers based on the author
Adding other group members to reviewers if group assignment feature is on
Group assignment feature is disabled
Randomly picking reviewers if the number of reviewers is set
Requesting review to team:mds-platform
Error: HttpError: Validation Failed: "Could not resolve to a node with the global id of 'T_kwDOBzcd9M4Adqj[8](https://github.com/mds-emu/CR-Test-Repo/actions/runs/9117703018/job/25113345970#step:2:9)'."
```

Error when I remove the team from access the repo: 
```
Error: HttpError: Reviews may only be requested from collaborators. One or more of the teams you specified is not a collaborator of the mds-emu/CR-Test-Repo repository.
```</div>

**Comment by felix-schaipp** [comment]
It also took me quite a few runs to figure out a setup that works. 
I did the following:
- Create a PAT (personal access token) scoped to the repo with the following permissions:
  - Members: read and write, Team discussions: read and write, Metadata: read-only, Pull Requests: read and write
- make sure your team name is correct
- modify your action checkout the repo and use a local config as the token has no access writes otherwise (might also be controllable via another permission, but didn't dare to try)
Here is what my action ended up looking:

```yml
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  assign-reviewer:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Auto request review
          uses: necojackarc/auto-request-review@v0.13.0
          with:
            token: ${{ secrets.TOKEN_TEAM_ASSIGNMENT }}
            config: .github/reviewers.yml
            use_local: true

```
 Hope that helps!
Plus for testing make sure you add `pull_request` as a trigger for your action otherwise the changes to your yml might not get picked up.
