### ISSUE TITLE
Allow for specifying reviewers for each member

### ISSUE THREAD

**Issue by necojackarc** [necojackarc/auto-request-review#25]
The current implementation is best for the teams where all members review all PRs.
However, in some teams, the following case can happen, for instance:

* Head of Design reviews only Lead Designer's changes
* Lead Designer reviews Head of Design's, Member A's and B's changes
* Member A reviews Lead Designer's changes
* Member B doesn't review changes at all

In other words,

* Member A has Lead Designer review their code
* Member B has Lead Designer review their code
* Lead Designer has Member A and Head of Design review their code

| reviewer \ reviewee | Head of Design | Lead Designer | Member A | Member B |
| --- |  --- | --- | --- | --- |
|  Head of Design | - | Y | N | N |
| Lead Designer | Y | - | Y | Y |
| Member A | N | Y | - | N |
| Member B | N | N | N | - |

## Solution
Add a `per_author` key to `reviewers`. The settings file will look like:

```yaml
reviewers:
  defaults:
    - engineers

  groups:
    engineers:
      - engineer_a
      - engineer_b
      - engineer_c
    designers:
      - head_of_design
      - lead_designer
      - desinger_a
      - designer_b

  # Reviwers for each author
  per_author:
    engineers:
      - engineers
    head_of_design:
      - lead_designer
    lead_designer:
      - head_of_design
      - designer_a
    designer_a:
      - lead_designer
    designer_b:
      - lead_desinger
```
