### ISSUE TITLE
Using default reviews and files, no reviewers are matched

### ISSUE THREAD

**Issue by bbugh** [necojackarc/auto-request-review#51]
Hi! 👋 Thanks for making this action, it looks like exactly what we need. Unfortunately, it isn't working.

I'm not quite sure what is wrong here, but the expectation is that any files outside of the two directories would be automatically assigned to `team:leads`

With files changed in `.github`, given this configuration:

```yml
reviewers:
  default:
    - team:leads

files:
  'clients/**':
    - team:frontend
    - team:leads
  'api/**':
    - team:backend
    - team:leads

options:
  ignore_draft: true
```

No reviewers are assigned:

```
Run necojackarc/auto-request-review@e08cdffa277d50854744de3f76230260e61c67f4
  with:
    token: ***
    config: .github/auto_request_review.yml
Fetching configuration file from the source branch
Fetching changed files in the pull request
Identifying reviewers based on the changed files
Identifying reviewers based on the author
"per_author" is not set; returning no reviewers for the author.
Adding other group membres to reviewers if group assignment feature is on
Group assignment feature is disabled
Matched no reviewers
No default reviewers are matched; terminating the process
```

So I tried a `**` glob, and still none are assigned:

```yml
files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  'clients/**':
    - team:frontend
    - team:leads
  'api/**':
    - team:backend
    - team:leads
  '**':
    - team:leads

options:
  ignore_draft: true
```

Same result:

```
Run necojackarc/auto-request-review@e08cdffa277d50854744de3f76230260e61c67f4
  with:
    token: ***
    config: .github/auto_request_review.yml
Fetching configuration file from the source branch
Fetching changed files in the pull request
Identifying reviewers based on the changed files
Identifying reviewers based on the author
"per_author" is not set; returning no reviewers for the author.
Adding other group membres to reviewers if group assignment feature is on
Group assignment feature is disabled
Matched no reviewers
No default reviewers are matched; terminating the process
```

Is this a bug? Have I missed something? Thank you!

**Comment by bbugh** [comment]
Ack - after reading the README ten times, just after posting this I finally grokked the part about the PAT. Sorry!

**Comment by bbugh** [comment]
Ok, nevermind, even using the PAT it does not seem to be working.

The job looks like this:

```yml
# .github/workflows/auto_request_review.yml
name: Auto Request Review

on:
  pull_request:
    # FIXME: Once this is working, uncomment
    # types: [opened, ready_for_review, reopened]

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: necojackarc/auto-request-review@e08cdffa277d50854744de3f76230260e61c67f4 # v0.7.0
        with:
          token: ${{ secrets.AUTO_REQUEST_REVIEW_PAT }}
          config: .github/auto_request_review.config.yml # Testing this too, no good
```

And then tried with both configurations from the issue description.
