### ISSUE TITLE
auto-request-review doesn't add reviewers from github team.

### ISSUE THREAD

**Issue by lurbanski-equinix** [necojackarc/auto-request-review#55]
Hi,
Normal configuration with list of reviewer works. Thanks a lot. It is very useful action.

I have an issue with using github team. The action doesn't add reviewers from a github team.

Logs:
```bash
with:
    token: ***
    config: .github/config/reviewers.yaml
Fetching configuration file from the source branch
Fetching changed files in the pull request
Identifying reviewers based on the changed files
A "files" key does not exist in config; returning no reviewers for changed files.
Identifying reviewers based on the author
Adding other group members to reviewers if group assignment feature is on
Group assignment feature is enabled
Randomly picking reviewers if the number of reviewers is set
Requesting review to team:my-team
```

Configuration:
```yaml
- name: Auto request review
   uses: necojackarc/auto-request-review@91e252d75fe335f586be7e243c39e5dd88f2e153
   with:
      token: ${{ secrets.GIT_PAT }}
      config: .github/config/reviewers.yaml
```

reviewers.yaml
```yaml
reviewers:
  per_author:
    lurbanski-equinix:
      - team:my-team

options:
  ignore_draft: false
  enable_group_assignment: true
```

I also tried to set "Enable auto assignment" in the team settings, but it doesn't work as well.
My GIT_PAT has full access to repo.
