### ISSUE TITLE
How to re-request review

### ISSUE THREAD

**Issue by phbissiwu** [necojackarc/auto-request-review#56]
I would like to know how can I re-request reviews. it seems there is no way to do this with the current version.

**Comment by necojackarc** [comment]
@phbissiwu It depends on when you'd like to trigger the GitHub action. If you watch the following events,

```
on:
  pull_request:
    types: [opened, ready_for_review, reopened]
```

when you get a PR back to draft, then make it ready for review again, the action will be triggered, so it'll re-request reviews. If you don't like such a workflow and embed a command in a commit, there's no way at this moment.

**Comment by necojackarc** [comment]
@phbissiwu It sounds like you could use `Labels` to trigger the action to re-assign reviewers:

```yaml
on:
  pull_request:
    types: [labeled]
jobs:
  build:
    if: ${{ github.event.label.name == 'ReviewRequest' }}
    runs-on: ubuntu-latest
```

Mostly copied from: https://github.com/necojackarc/auto-request-review/issues/57#issuecomment-1046108267
Thanks to @gdegirmenci
