### ISSUE TITLE
Add condition according to label

### ISSUE THREAD

**Issue by acepaceNS** [necojackarc/auto-request-review#57]
Not sure if there's an alternative option

Would you be open a PR adding option to add reviewers according to labels?

**Comment by gdegirmenci** [comment]
as far I see, there's no such a feature -yet. but what you could do, conditionally, you could run the specific step based on the label you are looking for. 

```yaml
name: CI
on:
  pull_request:
    types: [labeled]
jobs:
  build:
    if: ${{ github.event.label.name == 'BUG' }}
    runs-on: ubuntu-latest
```
