### ISSUE TITLE
File matched, but no assignment occurred

### ISSUE THREAD

**Issue by dep** [necojackarc/auto-request-review#66]
Looking at my output, I see the following:

```
Run shufo/auto-assign-reviewer-by-files@v1.1.3
{
  '.github/**/*.yml': [ 'dep' ],
  'config/**/*': [ 'dep' ],
  'scripts/*': [ 'dep' ],
  'package.json': [ 'dep' ],
  'manifest.json': [ 'dep' ],
  Makefile: [ 'dep' ]
}
  .github/assign-by-files.yml matches .github/**/*.yml
  Makefile matches Makefile
finished!
```

Though no assignment occurred in the PR:

![CleanShot 2022-06-24 at 15 16 56](https://user-images.githubusercontent.com/55112925/175650692-67f191e2-1fa3-41a4-ab08-bbbbbc546f29.png)

Workflow:
```
name: "👷🏻‍♂️ Auto Assign"
on:
  - pull_request

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: shufo/auto-assign-reviewer-by-files@v1.1.3
        with:
          config: ".github/assign-by-files.yml"
          token: ${{ secrets.GITHUB_TOKEN }}
```

Config:
```
---
".github/**/*.yml":
  - dep

"config/**/*":
  - dep

"scripts/*":
  - dep

"package.json":
  - dep

"manifest.json":
  - dep

"Makefile":
  - dep
```

Thanks for any help!
