### ISSUE TITLE
Support for monorepo / cross-team repositories

### ISSUE THREAD

**Issue by seanbecker15** [necojackarc/auto-request-review#85]
I'm hoping to inquire whether the following use-case is supported:

Team 1 - Maintainers
Team 1 - Contributors
Team 2 - Maintainers
Team 2 - Contributors

For a given glob, require review from 1 member of each maintainer group and the rest of the contributor group of the member who created the pull request.

This is an important use-case for repositories used across multiple teams (i.e., monorepos). Happy to elaborate and work toward a solution if this is not possible. Thanks!

**Comment by necojackarc** [comment]
Unfortunately, it doesn't support that use case. The biggest blocker is the option for the maximum number of reviewers applied to the whole reviewer selection.

Let's say five reviewers are chosen based on files changed *and* teams, and you have `options.number_of_reviewers = 3`. The random three will be picked out of these five. This is because the randomise logic comes at the very end.

https://github.com/necojackarc/auto-request-review/blob/2cfdd67e9063122f02c9bd05b6aac58746c854f1/src/index.js#L71-L75

Off the top of my head, I can think of something like `options.groups.[group_name].number_of_reviewers`.

I'm not sure if this is a good idea, but I *think* your case could be covered with this option:

```yaml
reviewers:
  groups:
    team_1_maintainers:
      - member_a
    team_1_contributors:
      - member_b
    team_2_maintainers:
      - member_c
    team_2_contributors:
      - member_d

  per_author:
    team_1_contributors:
      - team_1_maintainers
      - team_1_contributors

    team_2_contributors:
      - team_2_maintainers
      - team_2_contributors

options:
  groups:
    team_1_maintainers:
      number_of_reviewers: 1
    team_2_maintainers:
      number_of_reviewers: 1
```
