### ISSUE TITLE
Trying to parse config throwing vague error

### ISSUE THREAD

**Issue by skellertor** [necojackarc/auto-request-review#86]
Here is my config file labeled `reviewers.yml`

```yaml
reviewers:
  # The default reviewers
  defaults:
    - team:core-qa # GitHub team

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    qa:
      - team:core-qa
    engineers:
      - team:core-fe-devs

  # Reviewers per author.
  # Keys are reviewees, each of which has an array of reviewers.
  per_author:
    engineers:
      - team:core-qa # GitHub team
```

Whenever I run the action I get this error:
`Error: TypeError: Cannot read properties of undefined (reading 'title')`

There is no title key in the yaml file. Have you faced this issue before? What is wrong with my config file that causes this typerror?
